### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tschallacka** [coolAlias/Tutorial-Demo#3]
Under what license does this tutorial code fall?

This is important because in 1 year and 11 months ish the new European copyright law will go in effect and such, and I need a paper trail of licenses and such.

**Comment by coolAlias** [comment]
Sorry for the late reply - luckily you were super-proactive!

My other Minecraft-related projects use GPL3, so I'll use that here as well. When I get a chance, I'll officially add the license to the repo.

**Comment by tschallacka** [comment]
Oh thats a shame, that means i cant use it.
Gplv3 can't be linked from from other licensend code unlike lgplv2. It's the license issue that killed bukkit.

I'll scrap your code out of my codebase. Thanks for the tutorials though.

**Comment by coolAlias** [comment]
I don't have any strong feelings (or much knowledge, to be honest) about any particular license, and have no issues with you using my code.

I can use LGPLv2 or MIT or whatever would work for you.

**Comment by tschallacka** [comment]
Lgplv2 is fine, it has much in the direction of your usual preference of license.

In a nutshell:

Technically, if you use gplv3 with your other code, nobody can use your code without violating the license, because minecraft itself is close sourced and incompatible and excluded by gplv3 as a linking against library.

So you can use it because its your code, but for everyone else its look, but don't touch. 

I would advice MIT only if you're OK that other people can sell your code in their software, and only have to supply the license along with it.
With lgplv2 you're forcing the open source bit.

**Comment by coolAlias** [comment]
Thanks for the suggestion - lgplv2 it is.
